feat: add data import/export commands
zitadel/zitadel-tools pull request #156
Opened 2024-06-26 16:39 UTC by yann-soubeyrand

This simplifies the provisioning of local development environments. One can setup its organization, project, users, etc, and export instance data to a JSON file. Then, when creating a new development environment, the JSON file can be imported to the newly created instance.

2024-07-09 15:49 UTC, muhlemmer requested changes
Thanks for the PR! This is a great contribution. I've left a few comments that will need to be resolved.

2024-07-09 15:49 UTC, muhlemmer commented on cmd/data/import/import.go
Using the exported json file, the import fails with:

```
go run main.go data import --api=localhost:8080 --insecure --issuer=http://localhost:8080 --key=275218352408933106.json --data=export.json
2024/07/09 17:29:23 failed to unmarshal data: proto: (line 1:2): unknown field "orgs"
exit status 1
```

That's because the Request has a Oneof field that has to be populated first. I'll make a suggestion below in the file.

2024-07-09 15:49 UTC, muhlemmer commented on cmd/data/import/import.go
> +	resp, err := client.ImportData(context.Background(), &req)
Use the propper message type for unmarshall like this:


```suggestion
	var reqOrgs pb.ImportDataOrg

	err = protojson.Unmarshal(data, &reqOrgs)

	if err != nil {
		log.Fatalln("failed to unmarshal data:", err)
		return
	}

	resp, err := client.ImportData(context.Background(), &pb.ImportDataRequest{
		Data: &pb.ImportDataRequest_DataOrgs{
			DataOrgs: &reqOrgs,
		},
		Timeout: "5m", // TODO: from command line argument!
	})
```

Timeout is a required field and will need to be parsed from the command line arguments as well.

2024-07-09 15:49 UTC, muhlemmer commented on cmd/data/data.go
> +	insecure := Cmd.PersistentFlags().Bool("insecure", false, "disable TLS to connect to gRPC API (use for local development only)")
I feel that these 3 command line options are quite redundant.

For example:

1. If the issuer is `http://localhost:8080`, you already know the API endpoint is `localhost:8080` and the connection is insecure.
2. If the issuer is `https://<instance>.zitadel.cloud`, you already know the API endpoint is `<instance>.zitadel.cloud:443` and the connection is secure.

For this example you'll need to parse the URL of the issuer and imply the the API configuration from there.

The reverse can also be applied:

1. A `--host` flag can point to the API and will become part of the issuer
2. The `--insecure` flag toggles `https` to `http` in front of the issuer. The API port toggles between `443` and `80` by default.
3. A `--port` flag sets / overrides the port suffix to the host for the issuer and API.

In the last example, if one would only set `<instance>.zitadel.cloud`, the default will create issuer `https://<instance>.zitadel.cloud` and API endpoint `<instance>.zitadel.cloud:443`.

For user friendlyness I would want to stick to one of the above solutions, you may pick one.

2024-08-20 14:19 UTC, muhlemmer commented
Hi @yann-soubeyrand, do you intend to continue work on this PR?

2024-08-20 14:39 UTC, yann-soubeyrand commented
Hi @muhlemmer, sorry for the late reply. Yes, I’d be glad to work on this again, but I’ve just no time for it for the moment. My first intention when I opened this PR was to share the code which I used in a project.

2024-12-02 09:52 UTC, muhlemmer commented
Closing as comments are not being resolved. Feel free to reopen when there is more time to resolve them.

2024-12-02 09:52 UTC, closed without merging